name: Feature request
description: Suggest an idea for the integration
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve
      description: Describe what you're trying to do that the integration doesn't support today
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What you'd like to see
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Workarounds or alternatives you've considered
